### ISSUE TITLE
Cannot find file - premailer_railtie

### ISSUE THREAD

**Issue by djsegal** [stuyam/bootstrap-email#12]
Getting the following load error after adding your gem:

```ruby
/Users/dan/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- bootstrap-email/premailer_railtie (LoadError)
	from /Users/dan/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
```

Any clue as to why it's not finding that file?

**Comment by FarazPatankar** [comment]
Hey @djsegal,
I had the same issue. For now, you can try building your gem with the master branch and then it should work. Fingers crossed it gets fixed soon.

**Comment by stuyam** [comment]
Update to the most recent release, v0.2.1 and let me know if that works.

**Comment by FarazPatankar** [comment]
Tried it on 0.2.2 but it looks the there's another issue with it. You can see it here: #14

**Comment by FarazPatankar** [comment]
I know you've already closed it but thought I'd mention that it works fine on the most recent release.
