### ISSUE TITLE
Negative Argument error

### ISSUE THREAD

**Issue by JaisonBrooks** [stuyam/bootstrap-email#24]
Im getting a Negative argument error and unsure why this is happening.

`make_bootstrap_mail(to: @to, bcc: ['example@example.com', 'example2@example.com'], subject: @subject)`

The above is called in a method from my Mailer class that is linked to the layout file by the same name.

Stack...
```
vendor/bundle/gems/bootstrap-email-0.2.4/lib/bootstrap-email.rb:217:in `*': negative argument (ArgumentError)
    from vendor/bundle/gems/bootstrap-email-0.2.4/lib/bootstrap-email.rb:217:in `preview_text'
    from vendor/bundle/gems/bootstrap-email-0.2.4/lib/bootstrap-email.rb:209:in `block in body'
    from vendor/bundle/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:204:in `block in each'
    from vendor/bundle/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `upto'
    from vendor/bundle/gems/nokogiri-1.8.5/lib/nokogiri/xml/node_set.rb:203:in `each'
    from vendor/bundle/gems/bootstrap-email-0.2.4/lib/bootstrap-email.rb:208:in `body'
    from vendor/bundle/gems/bootstrap-email-0.2.4/lib/bootstrap-email.rb:41:in `compile_html!'
    from vendor/bundle/gems/bootstrap-email-0.2.4/lib/bootstrap-email.rb:22:in `perform_full_compile'
    from vendor/bundle/gems/bootstrap-email-0.2.4/lib/bootstrap-email/action_mailer.rb:10:in `make_bootstrap_mail'
    from app/mailers/service_mailer.rb:17:in `support_request'
    from vendor/bundle/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:194:in `process_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
    from vendor/bundle/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134:in `process'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/rescuable.rb:25:in `block in process'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/rescuable.rb:24:in `process'
    from vendor/bundle/gems/actionview-5.2.1/lib/action_view/rendering.rb:32:in `process'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/base.rb:607:in `block in process'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/base.rb:606:in `process'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/message_delivery.rb:123:in `block in processed_mailer'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/message_delivery.rb:122:in `tap'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/message_delivery.rb:122:in `processed_mailer'
    from vendor/bundle/gems/actionmailer-5.2.1/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
    from app/controllers/systems/support_requests_controller.rb:89:in `create'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:194:in `process_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
    from vendor/bundle/gems/actionpack-5.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/notifications.rb:168:in `instrument'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
    from vendor/bundle/gems/activerecord-5.2.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
    from vendor/bundle/gems/actionpack-5.2.1/lib/abstract_controller/base.rb:134:in `process'
    from vendor/bundle/gems/actionview-5.2.1/lib/action_view/rendering.rb:32:in `process'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_controller/metal.rb:191:in `dispatch'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_controller/metal.rb:252:in `dispatch'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `each'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `serve'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
    from vendor/bundle/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:189:in `call!'
    from vendor/bundle/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
    from vendor/bundle/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
    from vendor/bundle/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
    from vendor/bundle/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15:in `call'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/conditional_get.rb:38:in `call'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
    from vendor/bundle/gems/railties-5.2.1/lib/rails/rack/logger.rb:38:in `call_app'
    from vendor/bundle/gems/railties-5.2.1/lib/rails/rack/logger.rb:26:in `block in call'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
    from vendor/bundle/gems/railties-5.2.1/lib/rails/rack/logger.rb:26:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
    from vendor/bundle/gems/activesupport-5.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
    from vendor/bundle/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
    from vendor/bundle/gems/actionpack-5.2.1/lib/action_dispatch/middleware/ssl.rb:74:in `call'
    from vendor/bundle/gems/railties-5.2.1/lib/rails/engine.rb:524:in `call'
    from vendor/bundle/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
    from vendor/bundle/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
    from vendor/bundle/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
    from vendor/bundle/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
    from vendor/bundle/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `call'
    from vendor/bundle/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by typarker** [comment]
I had this issue too and found that if I remove any punctuation from the <preview> tag it fixed the issue.

**Comment by typarker** [comment]
Actually I think it might be a length issue.  If I make the preview section too long, the negative argument error is thrown.

**Comment by cmcguff-myob** [comment]
Yeah, it's a length problem - I have to `.truncate(100)` before it works.

**Comment by stuyam** [comment]
Fixed in latest release: https://github.com/stuyam/bootstrap-email/releases/tag/0.3.2
